name: external_modules
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # ========== 核心框架 ==========
  get: 4.7.2  # 状态管理/路由/依赖注入  <<  get: ^4.7.2

  # ========== UI & 交互 ==========
  bot_toast: 4.1.3  # 轻量级Toast组件  <<  flutter_easyloading: 3.0.5
  flutter_easyloading: 3.0.5
#  dropdown_button2: 2.3.9  # 增强型下拉框  <<  dropdown_button2: ^2.0.0
  flutter_staggered_grid_view: 0.7.0  # 瀑布流布局  <<  flutter_staggered_grid_view: ^0.7.0
  extended_nested_scroll_view: ^6.2.1
  flutter_slidable: ^4.0.3
  flutter_reorderable_grid_view: ^3.1.3


  # ========== 网络通信 ==========
  dio: 5.9.0  # 强大的HTTP客户端  <<  dio: ^5.9.0
  web_socket_channel: 3.0.3  # WebSocket支持  <<  web_socket_channel: ^3.0.0
  webview_flutter:
#  flutter_inappwebview: 6.0.0  # 增强版WebView  <<  webview_flutter: ^4.13.0

  # ========== 多媒体处理 ==========
  ## 音频
  record: 6.0.0  # 高性能录音  <<  record: ^6.0.0
  just_audio: 0.10.4  # 音频播放核心  <<  just_audio: ^0.10.4
  audioplayers: 6.5.0  # 音频功能扩展  <<  audioplayers: ^5.2.1

  ## 视频
  #  video_player: 2.10.0  # 官方视频播放  <<  video_player: ^2.10.0
  cached_video_player_plus: ^4.1.0

  ## 图像
  image_picker: 1.1.2  # 图片选择器  <<  image_picker: ^1.1.2
  image_cropper: 9.1.0  # 图片裁剪  <<  image_cropper: ^9.1.0
  image: 4.0.17  # 图像处理库  <<  image: ^4.0.17
  flutter_image_compress: 2.0.4  # 图片压缩  <<  flutter_image_compress: ^2.0.4
  image_gallery_saver_plus: ^4.0.1
  # ========== 数据管理 ==========
  get_storage: 2.1.1  # 轻量级键值存储  <<  shared_preferences: ^2.5.3
  sqflite_sqlcipher: ^3.2.1  # SQLite数据库  <<  sqflite: ^2.4.2

  cached_network_image: 3.4.1  # 图片缓存组件  <<  cached_network_image: ^3.4.1
  archive: 3.6.1  # 压缩/解压工具  <<  archive: ^3.1.2

  # ========== 设备功能 ==========
  path_provider: 2.1.4  # 文件路径访问  <<  path_provider: 2.1.2
  wakelock_plus: 1.3.2  # 屏幕常亮控制  << wakelock_plus: ^1.3.2
  permission_handler: 12.0.1  # 权限管理  <<  permission_handler: ^12.0.1
  flutter_secure_storage: 9.2.4 #keychain
  device_info_plus: 12.3.0

  # ========== 第三方SDK ==========
  adjust_sdk: 5.4.1  # Adjust数据分析  <<  adjust_sdk: ^5.4.1
#  tencent_trtc_cloud: 2.9.9  # 腾讯云TRTC  <<  tencent_trtc_cloud: ^2.9.9
  qcloud_cos_client: 0.0.7  # 腾讯云COS  <<  qcloud_cos_client: ^0.0.7
  sign_in_with_apple: 7.0.1  # Apple登录  <<  sign_in_with_apple: ^7.0.1
#  firebase_messaging: 16.0.2  # 消息推送

  # ========== 工具类 ==========
  intl: 0.20.2  # 国际化(日历)  <<  intl: ^0.18.2
  encrypt: 5.0.3  # 加密算法  <<  encrypt: ^5.0.3
  url_launcher: 6.1.14
  logger: 2.6.1
  flutter_screenutil: 5.9.3
#  flip_card: 0.7.0
#  card_swiper: 3.0.1
#  bubble_pop_up: ^2.1.0
#  video_thumbnail: ^0.5.6
#  flutter_linkify: 6.0.0

  flutter_svga:
    path: lib/flutter_svga

dependency_overrides:
  flutter_cache_manager:
    git:
      url: https://github.com/Oliver-WJ/flutter_cache_manager.git
      path: flutter_cache_manager
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
